version: '2'
services:
  php:
    image: laravel-php:latest
    restart: always
    volumes:
      - ${PROJECT_DIR}:/Project:cached
      - ~/.ssh:/root/.ssh
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
  nginx:
    image: nginx
    restart: always
    ports:
      - ${FRONTEND_PORT}:80
    volumes:
      - ${PROJECT_DIR}:/Project
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
  mariadb:
    image: mariadb:10.2
    restart: always
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - "MYSQL_DATABASE=laravel"
      - "MYSQL_USER=laravel"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    volumes:
      - ${DBDATA_DIR}:/var/lib/mysql:delegated
